services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    hostname: wg-easy
    container_name: sys_wg-easy

    devices:
      - /dev/net/tun

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    environment:
      - TZ=${TZ}
      - PASSWORD_HASH=${SYS_WG_EASY_PASSWORD}

      - WG_HOST=${SERVER_DOMAIN_PUBLIC}
      - WG_PORT=51820
      - WG_DEVICE=eth0
      - WG_MTU=1420

      # - WG_PRE_UP=iptables -t nat -I PREROUTING  -p udp --dport 53 -j DNAT --to-destination 127.0.0.11:53
      # - WG_PRE_DOWN=iptables -t nat -D PREROUTING  -p udp --dport 53 -j DNAT --to-destination 127.0.0.11:53
      # - WG_POST_UP=iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE;
      # - WG_POST_DOWN=iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE;

      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
      - WG_DEFAULT_ADDRESS=10.6.0.x
      - WG_PERSISTENT_KEEPALIVE=21
      - WG_DEFAULT_DNS=${LAN_IP},1.1.1.1

      - UI_TRAFFIC_STATS=true
      - UI_CHART_TYPE=1

    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1

    volumes:
      - ${DOCKER_DATA}/sys/wg-easy/wireguard:/etc/wireguard

    networks:
      default:
        aliases:
          - wg-easy
          - wstunnel

    expose:
      - 51820/udp # wg
      - 51821/tcp # interface

    ports:
      - 0.0.0.0:51820:51820/udp
      - 0.0.0.0:443:51820/udp

    labels:
      - com.centurylinklabs.watchtower.monitor-only=true
      - traefik.enable=true

      # Internal
      - traefik.http.routers.wg-easy_sys_internal.service=wg-easy_sys_internal
      - traefik.http.services.wg-easy_sys_internal.loadbalancer.server.port=51821
      - traefik.http.routers.wg-easy_sys_internal.entryPoints=websecure
      - traefik.http.routers.wg-easy_sys_internal.tls=true
      - traefik.http.routers.wg-easy_sys_internal.middlewares=auth, allow-private-cidr
      - traefik.http.routers.wg-easy_sys_internal.rule=Host(`wg-easy.${SERVER_DOMAIN_INTERNAL}`)

      # Localhost
      - traefik.http.routers.wg-easy_sys_localhost.service=wg-easy_sys_localhost
      - traefik.http.services.wg-easy_sys_localhost.loadbalancer.server.port=51821
      - traefik.http.routers.wg-easy_sys_localhost.entrypoints=web
      - traefik.http.routers.wg-easy_sys_localhost.middlewares=allow-localhost
      - traefik.http.routers.wg-easy_sys_localhost.rule=Host(`wg-easy.sys.docker.localhost`)

    restart: always
