services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: arr_prowlarr
    hostname: prowlarr

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${DOCKER_DATA}/arr/prowlarr/config:/config
      - ${DOCKER_ARR_POOL}:/pool

    networks:
      - default
    expose:
      - 9696

    labels:
      - traefik.enable=true

      # Public (shared)
      - traefik.http.routers.prowlarr_arr_public_shared.service=prowlarr_arr_public_shared
      - traefik.http.services.prowlarr_arr_public_shared.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr_arr_public_shared.entryPoints=websecure
      - traefik.http.routers.prowlarr_arr_public_shared.tls=true
      - traefik.http.routers.prowlarr_arr_public_shared.middlewares=auth
      - traefik.http.routers.prowlarr_arr_public_shared.rule=Host(`${SERVER_DOMAIN_PUBLIC}`) && PathRegexp(`^/prowlarr`)

      # Public API (shared)
      - traefik.http.routers.prowlarr-api_arr_public_shared.service=prowlarr-api_arr_public_shared
      - traefik.http.services.prowlarr-api_arr_public_shared.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr-api_arr_public_shared.entryPoints=websecure
      - traefik.http.routers.prowlarr-api_arr_public_shared.tls=true
      - traefik.http.routers.prowlarr-api_arr_public_shared.rule=Host(`${SERVER_DOMAIN_PUBLIC}`) && PathRegexp(`^/prowlarr(/[0-9]+)?/api.*$`)
      - traefik.http.routers.prowlarr-api_arr_public_shared.priority=9999

      # Public
      - traefik.http.routers.prowlarr_arr_public.service=prowlarr_arr_public
      - traefik.http.services.prowlarr_arr_public.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr_arr_public.entryPoints=websecure
      - traefik.http.routers.prowlarr_arr_public.tls=true
      - traefik.http.routers.prowlarr_arr_internal.middlewares=auth
      - traefik.http.routers.prowlarr_arr_public.rule=Host(`prowlarr.${SERVER_DOMAIN_PUBLIC}`)

      # Public API
      - traefik.http.routers.prowlarr-api_arr_public.service=prowlarr-api_arr_public
      - traefik.http.services.prowlarr-api_arr_public.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr-api_arr_public.entryPoints=websecure
      - traefik.http.routers.prowlarr-api_arr_public.tls=true
      - traefik.http.routers.prowlarr-api_arr_public.priority=9999
      - traefik.http.routers.prowlarr-api_arr_public.rule=Host(`prowlarr.${SERVER_DOMAIN_PUBLIC}`) && PathRegexp(`^/prowlarr(/[0-9]+)?/api.*$`)

      # Internal
      - traefik.http.routers.prowlarr_arr_internal.service=prowlarr_arr_internal
      - traefik.http.services.prowlarr_arr_internal.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr_arr_internal.entryPoints=websecure
      - traefik.http.routers.prowlarr_arr_internal.tls=true
      - traefik.http.routers.prowlarr_arr_internal.middlewares=auth, allow-private-cidr
      - traefik.http.routers.prowlarr_arr_internal.rule=Host(`prowlarr.${SERVER_DOMAIN_INTERNAL}`)

      # Localhost
      - traefik.http.routers.prowlarr_arr_localhost.service=prowlarr_arr_localhost
      - traefik.http.services.prowlarr_arr_localhost.loadbalancer.server.port=9696
      - traefik.http.routers.prowlarr_arr_localhost.entrypoints=web
      - traefik.http.routers.prowlarr_arr_localhost.middlewares=allow-localhost
      - traefik.http.routers.prowlarr_arr_localhost.rule=Host(`prowlarr.arr.docker.localhost`)

    restart: unless-stopped
