services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    hostname: flaresolverr
    container_name: arr_flaresolverr

    environment:
      - TZ={TZ}

    networks:
      - default
    expose:
      - 8191

    labels:
      - traefik.enable=true

    restart: unless-stopped
