services:
  unpackerr:
    image: docker.io/golift/unpackerr
    hostname: unpackerr
    container_name: arr_unpackerr

    user: ${PUID}:${PGID}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

      - UN_FILE_MODE=0774
      - UN_DIR_MODE=0775

      - UN_SONARR_0_URL=${ARR_SONARR_URL}
      - UN_SONARR_0_API_KEY=${ARR_SONARR_API_KEY}
      - UN_SONARR_0_PATHS_0=/pool
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=10m

      - UN_RADARR_0_URL=${ARR_RADARR_URL}
      - UN_RADARR_0_API_KEY=${ARR_RADARR_API_KEY}
      - UN_RADARR_0_PATHS_0=/pool
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=10m

    volumes:
      - ${DOCKER_ARR_POOL}:/pool

    networks:
      - default

    restart: unless-stopped
