services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: arr_jellyfin
    hostname: jellyfin

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MALLOC_TRIM_THRESHOLD=131072
      - JELLYFIN_PublishedServerUrl=https://${SERVER_DOMAIN_PUBLIC}/jellyfin

    volumes:
      - ${DOCKER_DATA}/arr/jellyfin/config:/config

      - ${DOCKER_STORAGE}/arr/jellyfin/config/data/data/subtitles:/config/data/data/subtitles
      - ${DOCKER_STORAGE}/arr/jellyfin/config/data/data/keyframes:/config/data/data/keyframes

      - ${DOCKER_ARR_POOL}:/pool

    devices:
      - /dev/dri:/dev/dri

    networks:
      - default

    ports:
      - ${LAN_IP}:7359:7359/udp
      - ${LAN_IP}:1900:1900/udp

    expose:
      - 1900/udp
      - 7359/udp
      - 8096/tcp
      - 8920/tcp

    labels:
      - traefik.enable=true

      # Public (shared)
      - traefik.http.routers.jellyfin_arr_public_shared.service=jellyfin_arr_public_shared
      - traefik.http.services.jellyfin_arr_public_shared.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin_arr_public_shared.entryPoints=websecure
      - traefik.http.routers.jellyfin_arr_public_shared.tls=true
      - traefik.http.routers.jellyfin_arr_public_shared.rule=Host(`${SERVER_DOMAIN_PUBLIC}`) && PathPrefix(`/jellyfin`)

      # Public (Alt)
      - traefik.http.routers.jellyfin_arr_public.service=jellyfin_arr_public
      - traefik.http.services.jellyfin_arr_public.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin_arr_public.entryPoints=websecure
      - traefik.http.routers.jellyfin_arr_public.tls=true
      - traefik.http.routers.jellyfin_arr_public.rule=Host(`jellyfin.${SERVER_DOMAIN_PUBLIC}`)

      # Internal
      - traefik.http.routers.jellyfin_arr_internal.service=jellyfin_arr_internal
      - traefik.http.services.jellyfin_arr_internal.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin_arr_internal.entryPoints=websecure
      - traefik.http.routers.jellyfin_arr_internal.tls=true
      - traefik.http.routers.jellyfin_arr_internal.middlewares=allow-private-cidr
      - traefik.http.routers.jellyfin_arr_internal.rule=Host(`jellyfin.${SERVER_DOMAIN_INTERNAL}`)

      # Localhost
      - traefik.http.routers.jellyfin_arr_localhost.service=jellyfin_arr_localhost
      - traefik.http.services.jellyfin_arr_localhost.loadbalancer.server.port=8096
      - traefik.http.routers.jellyfin_arr_localhost.entrypoints=web
      - traefik.http.routers.jellyfin_arr_localhost.middlewares=allow-localhost
      - traefik.http.routers.jellyfin_arr_localhost.rule=Host(`jellyfin.arr.docker.localhost`)

    restart: unless-stopped
