services:
  miniserve:
    image: docker.io/svenstaro/miniserve
    container_name: arr_miniserve

    command: /pool

    environment:
      - MINISERVE_ROUTE_PREFIX=/files

    volumes:
      - ${DOCKER_ARR_POOL}:/pool:ro

    networks:
      - default
    expose:
      - 8080

    labels:
      - traefik.enable=true

      # Public (shared)
      - traefik.http.routers.miniserve_arr_public_shared.service=miniserve_arr_public_shared
      - traefik.http.services.miniserve_arr_public_shared.loadbalancer.server.port=8080
      - traefik.http.routers.miniserve_arr_public_shared.entryPoints=websecure
      - traefik.http.routers.miniserve_arr_public_shared.tls=true
      - traefik.http.routers.miniserve_arr_public_shared.rule=Host(`${SERVER_DOMAIN_PUBLIC}`) && PathPrefix(`/files`)
      - traefik.http.routers.miniserve_arr_public_shared.middlewares=auth, miniserve-redirect

      # Public (shared) middleware: rewriting /files/
      - traefik.http.middlewares.miniserve-stripprefix.stripprefix.prefixes=/files
      - traefik.http.middlewares.miniserve-redirect.redirectregex.regex=^https:\/\/([^\/]+)\/files$
      - traefik.http.middlewares.miniserve-redirect.redirectregex.replacement=https://$${1}/files/

      # Public
      - traefik.http.routers.miniserve_arr_public.service=miniserve_arr_public
      - traefik.http.services.miniserve_arr_public.loadbalancer.server.port=8080
      - traefik.http.routers.miniserve_arr_public.entryPoints=websecure
      - traefik.http.routers.miniserve_arr_public.tls=true
      - traefik.http.routers.miniserve_arr_public=auth
      - traefik.http.routers.miniserve_arr_public.rule=Host(`miniserve.${SERVER_DOMAIN_PUBLIC}`)

      # Internal
      - traefik.http.routers.miniserve_arr_internal.service=miniserve_arr_internal
      - traefik.http.services.miniserve_arr_internal.loadbalancer.server.port=8080
      - traefik.http.routers.miniserve_arr_internal.entryPoints=websecure
      - traefik.http.routers.miniserve_arr_internal.tls=true
      - traefik.http.routers.miniserve_arr_internal.middlewares=auth, allow-private-cidr
      - traefik.http.routers.miniserve_arr_internal.rule=Host(`miniserve.${SERVER_DOMAIN_INTERNAL}`)

      # Localhost
      - traefik.http.routers.miniserve_arr_localhost.service=miniserve_arr_localhost
      - traefik.http.services.miniserve_arr_localhost.loadbalancer.server.port=8080
      - traefik.http.routers.miniserve_arr_localhost.entrypoints=web
      - traefik.http.routers.miniserve_arr_localhost.middlewares=allow-localhost
      - traefik.http.routers.miniserve_arr_localhost.rule=Host(`miniserve.arr.docker.localhost`)

    restart: unless-stopped
