services:
  searcharr:
    #image: toddrob/searcharr:latest
    build: https://github.com/klementng/searcharr.git
    pull_policy: never

    container_name: arr_searcharr
    hostname: searcharr

    environment:
      - TZ=${TZ}

      - SEARCHARR_PASSWORD=${ARR_SEARCHARR_PASSWORD}
      - SEARCHARR_ADMIN_PASSWORD=${ARR_SEARCHARR_ADMIN_PASSWORD}
      - TGRAM_TOKEN=${ARR_SEARCHARR_TGRAM_TOKEN}
      - SONARR_URL=${ARR_SONARR_URL}
      - SONARR_API_KEY=${ARR_SONARR_API_KEY}
      - RADARR_URL=${ARR_RADARR_URL}
      - RADARR_API_KEY=${ARR_RADARR_API_KEY}

      - SONARR_QUALITY_PROFILE_ID=Remux-1080p - Anime,WEB-1080p
      - SONARR_TAG_WITH_USERNAME=False
      - SONARR_ALLOW_USER_TO_SELECT_TAGS=False
      - SONARR_SERIES_COMMAND_ALIASES=series,tv

      - RADARR_QUALITY_PROFILE_ID=HD Bluray + WEB
      - RADARR_TAG_WITH_USERNAME=False
      - RADARR_ALLOW_USER_TO_SELECT_TAGS=False
      - SONARR_SERIES_COMMAND_ALIASES=movies,m
      - READARR_ENABLED=False

    volumes:
      - ${DOCKER_DATA}/arr/searcharr/app/data:/app/data
      - ${DOCKER_DATA}/arr/searcharr/app/logs:/app/logs
      - ${DOCKER_DATA}/arr/searcharr/app/settings.py:/app/settings.py

    networks:
      - default

    restart: unless-stopped
